config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/search', controller: "myhome", action: "search"
  
  resources :mygems do
    resources :previews
  end

  resources :categories
  get '/my_activity', controller: "myhome", action: "activity"

  root :to => 'myhome#index'
  # root :to => 'mygems#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :mygems

    validates :name, presence: true
end

app/models/mygem.rb
class Mygem < ApplicationRecord

    def self.add_user_query(user_query)
        @@search_query = user_query.to_s  
    end

    scope :gems_search, ->(n=@@search_query) { where("title LIKE ? OR description LIKE ?", "%#{n}%", "%#{n}%").order("created_at DESC") }

    belongs_to :user
    belongs_to :category
    has_many :previews

    validates :title, presence: true
    validates :description, presence: true
end

app/models/preview.rb
class Preview < ApplicationRecord
    belongs_to :mygem
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :mygems
  has_many :previews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

    def index
        @all_categories=Category.all.order("name ASC")
    end

    def show
        @one_category=Category.find_by(id: params[:id])
        @all_gems_under_this_category=Mygem.where(category_id: @one_category.id).paginate(page: params[:page], per_page: 5).order("created_at DESC")
    end
    
end

app/controllers/mygems_controller.rb
class MygemsController < ApplicationController
    before_action :authenticate_user!, only: [:new, :edit]

    def index
        # raise params
        @test=params[:starts_with]
        if params[:starts_with].blank?
            @all_gems=Mygem.all.paginate(page: params[:page], per_page: 5).order("created_at DESC")
        else
            search=params[:starts_with]
            @all_gems=Mygem.where("title LIKE ?", "#{search}%").paginate(page: params[:page], per_page: 5).order("created_at DESC")
        end
    end

    def show
        @one_gem=Mygem.find_by(id: params[:id])
        @all_previews=@one_gem.previews.order("created_at DESC")

        if @one_gem.previews.blank?
            @average_review=0
        else
            @average_review=@one_gem.previews.average("rating").round(2)
        end
    end

    def new
        @mygem=Mygem.new
        @all_categories=Category.all.map{ |c| [c.name, c.id] }
    end

    def create
        # raise params
        var_category=params[:c_id]
        var_title=params[:mygem][:title]
        var_desc=params[:mygem][:description]
        
        @mygem=Mygem.new(category_id: var_category, title: var_title, description: var_desc, user_id: current_user.id)
        if !@mygem.save
            flash[:alert] = "Please fill in all the fields, and try again!"
            redirect_to new_mygem_path
        else
            redirect_to mygems_path
        end
    end

    def edit
        @one_gem_edit=Mygem.find_by(id: params[:id])
        @all_categories=Category.all.map{ |c| [c.name, c.id] }
    end

    def update
        @one_gem_edit=Mygem.find_by(id: params[:id])
        var_category=params[:mygem][:category_id]
        var_title=params[:mygem][:title]
        var_desc=params[:mygem][:description]

        if @one_gem_edit.update(category_id: var_category, title: var_title, description: var_desc)
            redirect_to mygem_path(@one_gem_edit)
        else
            flash[:alert] = "Please fill in all the fields, and try again!"
            redirect_to edit_mygem_path(@one_gem_edit)
        end
    end

    def destroy
        @one_gem_destroy=Mygem.find_by(id: params[:id])
        @one_gem_destroy.destroy
        redirect_to mygems_path
    end

end

app/controllers/myhome_controller.rb
class MyhomeController < ApplicationController

    def index
    end

    def activity
        @my_created_gems=Mygem.all.where(user_id: current_user.id).order("created_at DESC")
    end

    def search
        @query=params[:search_query]
        Mygem.add_user_query(@query)
        @search_results=Mygem.gems_search.paginate(page: params[:page], per_page: 5)
    end

    def search_basic
        # raise params
        @query=params[:search_query]
        if @query.blank?
            @search_results=Mygem.all.paginate(page: params[:page], per_page: 5).order("created_at DESC")
        else
            @search_results=Mygem.where("title LIKE ? OR description LIKE ?", "%#{@query}%", "%#{@query}%").paginate(page: params[:page], per_page: 5).order("created_at DESC") 
        end
    end
    
end

app/controllers/previews_controller.rb
class PreviewsController < ApplicationController
    before_action :authenticate_user!, only: [:new, :edit]

    def new
        # raise params
        @one_gem=Mygem.find(params[:mygem_id])
        @review=Preview.new
    end

    def create
        # raise params
        @one_gem=Mygem.find(params[:mygem_id])
        var_rating=params[:preview][:rating]
        var_comment=params[:preview][:comment]
        Preview.create(rating: var_rating, comment: var_comment, mygem_id: params[:mygem_id], user_id: current_user.id)
        redirect_to mygem_path(@one_gem)
    end

    def edit
        # raise params
        @one_gem=Mygem.find(params[:mygem_id])
        @one_review=Preview.find_by(id: params[:id])
    end

    def update
        # raise params
        @one_gem=Mygem.find(params[:mygem_id])
        @one_review=Preview.find_by(id: params[:id])
        var_edited_rating=params[:preview][:rating]
        var_edited_comment=params[:preview][:comment]
        @one_review.update(rating: var_edited_rating, comment: var_edited_comment)
        redirect_to mygem_path(@one_gem)
    end

    def destroy
        # raise params
        @one_gem=Mygem.find(params[:mygem_id])
        @one_review=Preview.find_by(id: params[:id])
        @one_review.destroy
        redirect_to mygem_path(@one_gem)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/mygems_helper.rb
module MygemsHelper
end

app/helpers/myhome_helper.rb
module MyhomeHelper
end

app/helpers/previews_helper.rb
module PreviewsHelper
end

app/views/categories/index.html.erb
<div class="row">
<h1>Category Overview</h1>
<br>
<p class="category-para">To give you an overview of what open source libraries are available for a given task we group projects for common problems into categories. The catalog itself is available for contributions.</p>
</div>

<hr><br>

<div class="row">
<% @all_categories.each do |item| %>
    <div class="col-md-4">
        <div class="category-landing box-cat">
            <div><i class="fa fa-folder folder" aria-hidden="true"></i> <%= link_to item.name, category_path(item), class:"links-category" %></div>
        </div>
    </div>
<% end %>
</div>

app/views/categories/show.html.erb
<div class="col-md-10 col-md-offset-1">

    <h2><%= @one_category.name %></h2>
    <hr>

    <%= @all_gems_under_this_category.count %> GEMS FOUND IN TOTAL
    <br><br>
    <% if !@all_gems_under_this_category.empty? %>
        <% @all_gems_under_this_category.each do |item| %>
            <div style="border-bottom: 1px solid rgb(193, 196, 202); padding-top: 30px; padding-bottom: 30px;">
                <h3><%= link_to item.title, mygem_path(item) %></h3>
                <em>created <%= time_ago_in_words(item.created_at) %> ago</em>
                <br>
                <div class="desc-class-overflow"><%= item.description %></div>	
            </div>
        <% end %>
    <% else %>
        <h3>There are no gems currently in this category</h3>
    <% end %>

    <br><br>
    
    <div style="text-align: center">
        <%= will_paginate @all_gems_under_this_category, renderer: BootstrapPagination::Rails %>
    </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rajesh0101Final</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-default">
        <div class="container">
          <div class="navbar-header">
            <%= link_to "RubyGems.org", root_path, class: "navbar-brand" %>

            <%= form_tag("/search", :method => "get", class: 'navbar-form navbar-left') do %>  
              <div class="input-group">  
                <%= search_field_tag :search_query, params[:search_query], placeholder: "Search for gems", class: "form-control" %>  
                <div class="input-group-btn">  
                <%= button_tag "", :class => 'btn btn-info glyphicon glyphicon-search', style: "top: 0px;", :name => nil%>  
                </div>
              </div>  
            <% end %>

          </div>

          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to "ACTIVITY LOG", my_activity_path %></li>
              <li><%= link_to "CONTRIBUTE", new_mygem_path %></li>
            <% end %>

            <li><%= link_to "GEMS", mygems_path %></li>

            <% if user_signed_in? %>
              <li><%= link_to "SIGN OUT", destroy_user_session_path, method: :delete %></li>
            <% else %>	
              <li><%= link_to "SIGN IN", new_user_session_path %></li>
            <% end %>

            <li><%= link_to "SIGN UP", new_user_registration_path %></li>
          </ul>
        </div>
      </nav>

      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <div class="container">
        <%= yield %>
      </div>

  </body>
</html>

app/views/mygems/edit.html.erb
<div class="col-md-8 col-md-offset-2 reviews-box">
    
    <h1>Edit a Gem</h1>

    <%= simple_form_for @one_gem_edit do |f| %>
        <%= f.select :category_id, @all_categories %>
        <%= f.input :title, label:"Gem Name" %>
        <%= f.input :description, label:"Gem Description" %>
        <%= f.button :submit, "Submit", class: "btn btn-primary" %>
    <% end %>

</div>

app/views/mygems/index.html.erb
<h1>All Gems</h1>
<br>
<hr>
    <% my_var=97 %>
    <% while my_var<=122 %>
        <% if @test==my_var.chr %>
            <span style="padding-left: 18px; font-size: 40px;"><b><%= link_to my_var.chr, mygems_path(starts_with: my_var.chr), class: "active links-hover" %></b></span>
        <% else %>
            <span style="padding-left: 18px; font-size: 40px;"><b><%= link_to my_var.chr, mygems_path(starts_with: my_var.chr), class: "links-hover" %></b></span>
        <% end %>
        <% my_var=my_var+1 %>
    <% end %>
<hr>
<%= @all_gems.count %> GEMS FOUND IN TOTAL
<br><br>


<% if !@all_gems.blank? %>
    <% @all_gems.each do |item| %>
        <div style="border-bottom: 1px solid rgb(193, 196, 202); padding-top: 30px; padding-bottom: 30px;">
            <h3><%= link_to item.title, mygem_path(item), class: "links-only" %></h3> <em>created <%= time_ago_in_words(item.created_at) %> ago</em>
            
            <% if user_signed_in? %>
                <% if item.user_id==current_user.id %>
                    <span style="float: right">
                        <%= link_to mygem_path(item), method: :delete, data: { confirm: "Are you sure you want to delete?" } do %>
                            <i class="fa fa-trash fa-2x" aria-hidden="true" title="Delete"></i>
                        <% end %>
                    </span>

                    <span style="float: right">
                        <%= link_to edit_mygem_path(item) do %>
                            <i class="fa fa-pencil fa-fw fa-2x" aria-hidden="true" title="Edit"></i>
                        <% end %>
                    </span>
                <% end %>
            <% end %>
            
            <br>
            <div class="desc-class-overflow"><%= item.description %></div>	
        </div>
    <% end %>
<% else %>
        
<% end %>

<br>

<div style="text-align: center">
    <%= will_paginate @all_gems, renderer: BootstrapPagination::Rails %>
</div>

app/views/mygems/new.html.erb
<div class="col-md-8 col-md-offset-2 reviews-box">

<h1>Create a Gem</h1>

<%= simple_form_for @mygem do |f| %>

    <%= select_tag(:c_id, options_for_select(@all_categories), :prompt => "Select a category") %>
    <br><br>
    <%= f.input :title, label:"Gem Name" %>
    <%= f.input :description, label:"Gem Description" %>
    <br>
    <%= f.button :submit, "Submit", class: "btn btn-primary" %>

<% end %>

</div>

app/views/mygems/show.html.erb
<div class="col-md-10 col-md-offset-1">

    <div class="row">
        <span style="float:left;">
            <h1 class="show-heading"><%= @one_gem.title %></h1>
        </span>
        
        <span style="float:right;">
            <h1><%= @average_review %> / 5 <i class="fa fa-star checked-star" aria-hidden="true"></i></h1>
            <h4>(based on <%= @one_gem.previews.count %> reviews)</h4>
        </span>
    </div>

    <hr><br>

    <h4 style="opacity: 0.8"><%= @one_gem.description %></h4>

    <br><hr>

    <div class="row">
        <div class="col-md-4">
            <h3 class="desc-show-page">AUTHOR:</h3><span><%= @one_gem.user.email %><span>
            <h3 class="desc-show-page">Created:</h3> <%= time_ago_in_words(@one_gem.created_at) %> ago
            <h3 class="desc-show-page">Last updated:</h3> <%= time_ago_in_words(@one_gem.updated_at) %> ago
            <h3 class="desc-show-page">Category:</h3> <%= @one_gem.category.name %>
        </div>
    </div>

    <hr>

    <br><br><br><br><br><br>


    <div class="reviews-box">

        <h1>Reviews</h1>
        <% if user_signed_in? %>
            <% if @one_gem.user_id!=current_user.id %>
                <%= link_to "Add Reviews", new_mygem_preview_path(@one_gem), class:"btn-custom" %>
            <% end %>
        <% end %>

        <hr>

        <div class="row">

            <div class="col-md-10 col-md-offset-1">
                <% if @all_previews.count!=0 %>
                    <% @all_previews.each do |item| %>
                        <div style="border-bottom: 1px solid rgb(193, 196, 202); padding-top: 30px; padding-bottom: 30px;">
                            <h5><i class="fa fa-user-circle fa-2x"></i> <em> posted by <%= item.user.email %> <span style="float: right;"><%= time_ago_in_words(item.created_at) %> ago</span> </em></h5>
                            <br>
                            <div><%= item.rating %>/5 <i class="fa fa-star checked-star fa-sm" aria-hidden="true"></i></div>	
                            <div><%= item.comment %></div>
                            <br>

                            <% if user_signed_in? %>
                                <% if item.user_id==current_user.id %>
                                <%= link_to "Edit", edit_mygem_preview_path(@one_gem, item), class:"btn-custom" %>
                                <%= link_to "Delete", mygem_preview_path(@one_gem, item), method: :delete, data: { confirm: "Are you sure you want to delete?"}, class:"btn-custom" %>
                                <% end %>
                            <% end %>
                        </div>
                    <% end %>
                <% else %>
                    NO REVIEWS YET
                    <br><br>
                <% end %>

            </div>
        </div>
    </div>
    <br><br><br><br>
</div>

app/views/myhome/activity.html.erb
<div class="col-md-10 col-md-offset-1">

    <h1>Your Activity Log</h1>
    <hr><br><br>
    <% if !@my_created_gems.empty? %>
        <% @my_created_gems.each do |item| %>
            <% gen_url= "/mygems/"+item.id.to_s %>
            <a class="links-only-activity" href="<%= gen_url %>">
                <div style="border-bottom: 1px solid rgb(193, 196, 202); padding-top: 40px; padding-bottom: 40px;">
                    You created a gem <strong style="color: red"><%= item.title %></strong> <span style="float: right; color: black;"><%= time_ago_in_words(item.created_at) %> ago</span>
                    <div></div>
                </div>
            </a>
        <% end %>
    <% else %>
        <h3>You have no activity.</h3>
    <% end %>

</div>

app/views/myhome/index.html.erb
<div>
<h1>Find, install, and publish RubyGems.</h1>
</div>

<div class="row">
    <div class="col-md-8">
    <h4>RubyGems.org is the Ruby community’s gem hosting service. 
        Instantly publish your gems and find out more about available gems. 
        Become a contributor and improve the site yourself.</h4>
    </div>
</div>

<br>

<div class="row">
    <div class="col-md-2">
        <a class="btn btn-danger" href="/categories" role="button">Browse by category</a>
    </div>
</div>

app/views/myhome/search.html.erb
<h1>Search results <span style="font-size: 30px; color: red;"><em> (for <%= @query %>)</em></span></h1>
<hr>

<% if !@search_results.empty? %>
    <%= @search_results.count %> GEMS FOUND IN TOTAL
    <br>
    <% @search_results.each do |item| %>
        <div style="border-bottom: 1px solid rgb(193, 196, 202); padding-top: 30px; padding-bottom: 30px;">
            <h3><%= link_to item.title, mygem_path(item), class: "links-only" %></h3> 
            <em>created <%= time_ago_in_words(item.created_at) %> ago</em>
            <br>
            <div class="desc-class-overflow"><%= item.description %></div>
        </div>
    <% end %>
<% else %>
    <h5>NO GEMS FOUND</h5>
<% end %>

<br>

<div style="text-align: center">
    <%= will_paginate @search_results, renderer: BootstrapPagination::Rails %>
</div>

app/views/previews/edit.html.erb
<div class="col-md-8 col-md-offset-2 reviews-box">

    <h1>Edit a review</h1>
    <hr><br>

    <%= simple_form_for [@one_gem, @one_review] do |f| %>
        <%= f.input :rating, label:"Rating(out of 5)", input_html: { min: 0, max: 5} %>
        <%= f.input :comment, label:"Comment" %>
        <%= f.button :submit, "Submit", class: "btn btn-primary" %>
    <% end %>

</div>

app/views/previews/new.html.erb
<div class="col-md-8 col-md-offset-2 reviews-box">

    <h1>Add a review</h1>
    <hr><br>

    <%= simple_form_for [@one_gem, @review] do |f| %>
        <%= f.input :rating, label: "Rating(out of 5)", input_html: { min: 0, max: 5, value: f.object.rating || 0}  %>
        <%= f.input :comment, label:"Comment" %>
        <%= f.button :submit, "Submit", class: "btn btn-primary" %>
    <% end %>

</div>